### PR TITLE
improve how warning is displayed

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
image

### CODE REVIEW

**Comment by jarroyomorales** [comment]
Wow, much nicer than mine, thank you!

**Comment by JordiBForgeFlow** [comment]
But now that I think. What if you want to allow multiple periods for a leave type? Like allow christmas and august.

**Comment by jarroyomorales** [comment]
Thats true, I think I should add range lines to holiday status. Creating a holiday type for christmas holidays and another for august doesn't solve the problem in a lot of cases.

**Comment by etobella** [comment]
Well, I haven't found this case. On our company, an employee should choose:

* 30 days over the year (from 1 January to 30 June of the next year)
* 1 day on each quarter
* 1 day on Christmas
* 1 day on Easters

It was similar on my previously job (different ranges, but same behaviour).

Obviously, this days could be reduced if you became an employee in the last year.

**Pull request merged**
